trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
- job: CreateZip
  displayName: Create zip package

  steps:
  - script: |
      echo "[INFO] Installing zip package..."
      sudo apt update -y && sudo apt install -y zip
      echo "[INFO] Installation successful..."
      cd packages
      echo "[INFO] Zipping Martini package..."
      zip -qr $(Pipeline.Workspace)/allens-empty-package.zip allens-empty-package
      echo "[INFO] Zipping successful..."
    displayName: 'Zip'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Pipeline.Workspace)/allens-empty-package.zip
      ArtifactName: martini
      publishLocation: 'Container'
    displayName: 'Publish Artifact'